language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run build
  - npm run test:ci
deploy:
  provider: surge
  project: ./dist/
  domain: https://mklein.surge.sh
  skip_cleanup: true
notifications:
  email: false
