language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  directories:
    - "node_modules"
addons:
  firefox: latest
  chrome: stable
script:
  - npm run lint:ci
  - npm run build
  - npm run test:ci
deploy:
  provider: surge
  project: ./dist/
  domain: https://mklein.surge.sh
  skip_cleanup: true
  on:
    node: "node"
matrix:
  fast_finish: true
  allow_failures:
    - node: "lts/*"
notifications:
  email: false
